import { AbstractBlockchainController, IMessage, IMessageContent, IMessageCorruptedContent, IExtraEncryptionStrateryBulk, IExtraEncryptionStrateryEntry, MessageKey, PublicKey, BlockchainControllerFactory, Uint256, ISourceSubject } from '@ylide/sdk';
import Web3 from 'web3';
import { EVMNetwork, IEthereumMessage } from '../misc';
import { provider } from 'web3-core';
import { EventData } from 'web3-eth-contract';
import { EthereumNameService } from './EthereumNameService';
export declare class EthereumBlockchainController extends AbstractBlockchainController {
    private readonly options;
    web3Readers: {
        web3: Web3;
        blockLimit: number;
    }[];
    private blocksCache;
    readonly MESSAGES_FETCH_LIMIT = 50;
    readonly mailerContractAddress: string;
    readonly mailerFirstBlock: number;
    readonly registryContractAddress: string;
    readonly registryFirstBlock: number;
    readonly network: EVMNetwork;
    readonly chainId: number;
    readonly nameService: EthereumNameService | null;
    constructor(options?: {
        network?: EVMNetwork;
        mailerContractAddress?: string;
        registryContractAddress?: string;
        nameServiceAddress?: string;
        web3Readers?: provider[];
    });
    private tryGetNameService;
    defaultNameService(): EthereumNameService | null;
    init(): Promise<void>;
    getBalance(address: string): Promise<string>;
    executeWeb3Op<T>(callback: (w3: Web3, blockLimit: number, doBreak: () => void) => Promise<T>): Promise<T>;
    getRecipientReadingRules(address: string): Promise<any>;
    getAddressByPublicKey(publicKey: Uint8Array): Promise<string | null>;
    getPublicKeyByAddress(registryAddress: string, address: string): Promise<Uint8Array | null>;
    extractAddressFromPublicKey(publicKey: PublicKey): Promise<string | null>;
    extractPublicKeyFromAddress(address: string): Promise<PublicKey | null>;
    private getBlock;
    getLastBlockNumber(): Promise<number>;
    private getBlockNumberByTime;
    private binSearchBlocks;
    private doEventsRequest;
    private tryRequest;
    private eventCmpr;
    retrieveEventsByBounds(mailerAddress: string, subject: ISourceSubject, fromBlockNumber: number, toBlockNumber: number, limit?: number): Promise<EventData[]>;
    private _retrieveEventsSinceBlock;
    getDefaultMailerAddress(): string;
    private _retrieveMessageHistoryByTime;
    retrieveHistorySinceBlock(subject: ISourceSubject, fromBlock: number, firstMessage?: IMessage): Promise<import("@ylide/sdk").IMessageBase[]>;
    private _retrieveMessageHistoryByBounds;
    private iterateMailers;
    retrieveMessageHistoryByTime(sender: Uint256 | null, recipient: Uint256 | null, fromTimestamp?: number, toTimestamp?: number, limit?: number): Promise<IMessage[]>;
    retrieveMessageHistoryByBounds(sender: Uint256 | null, recipient: Uint256 | null, fromMessage?: IMessage, toMessage?: IMessage, limit?: number): Promise<IMessage[]>;
    retrieveBroadcastHistoryByTime(sender: Uint256 | null, fromTimestamp?: number, toTimestamp?: number, limit?: number): Promise<IMessage[]>;
    retrieveBroadcastHistoryByBounds(sender: Uint256 | null, fromMessage?: IMessage, toMessage?: IMessage, limit?: number): Promise<IMessage[]>;
    retrieveAndVerifyMessageContent(msg: IMessage): Promise<IMessageContent | IMessageCorruptedContent | null>;
    retrieveMessageContentByMsgId(msgId: string): Promise<IMessageContent | IMessageCorruptedContent | null>;
    private formatPushMessage;
    private formatBroadcastMessage;
    isAddressValid(address: string): boolean;
    processMessages(msgs: EventData[]): Promise<IEthereumMessage[]>;
    getExtraEncryptionStrategiesFromAddress(address: string): Promise<IExtraEncryptionStrateryEntry[]>;
    getSupportedExtraEncryptionStrategies(): string[];
    prepareExtraEncryptionStrategyBulk(entries: IExtraEncryptionStrateryEntry[]): Promise<IExtraEncryptionStrateryBulk>;
    executeExtraEncryptionStrategy(entries: IExtraEncryptionStrateryEntry[], bulk: IExtraEncryptionStrateryBulk, addedPublicKeyIndex: number | null, messageKey: Uint8Array): Promise<MessageKey[]>;
    uint256ToAddress(value: Uint256): string;
    addressToUint256(address: string): Uint256;
    compareMessagesTime(a: IMessage, b: IMessage): number;
}
export declare const evmFactories: Record<EVMNetwork, BlockchainControllerFactory>;
